"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./rake-admin.module.css";

type Page = { id: string; title: string; slug: string; thumbnail_url: string | null; categories?: string; themes?: string; status: string; featured: number; product_link_count: number; updated_at: string };
type Dashboard = { totals: number[]; recent: Page[] };
type Taxonomy = { id: string; name: string; slug: string };
type ProductLink = { id: string; page_id: string; title: string; slug: string; url: string; platform: string; market: string | null; enabled: number };
const nav = [["Dashboard", "/rake/"], ["Coloring Pages", "/rake/coloring-pages/"], ["Themes", "/rake/themes/"], ["Media", "/rake/media/"], ["Product Links", "/rake/product-links/"], ["SEO", "/rake/seo/"], ["Settings", "/rake/settings/"]];
const api = async <T,>(path: string, init?: RequestInit): Promise<T> => { const response = await fetch(`/api/rake/${path}`, { ...init, headers: { "content-type": "application/json", ...(init?.headers ?? {}) } }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error ?? "Request failed."); return response.json(); };

export function RakeAdmin() {
  const [pathname, setPathname] = useState("/rake/"); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [pages, setPages] = useState<Page[]>([]); const [categories, setCategories] = useState<Taxonomy[]>([]); const [themes, setThemes] = useState<Taxonomy[]>([]); const [selected, setSelected] = useState<string[]>([]); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const section = useMemo(() => pathname.split("/").filter(Boolean)[1] ?? "dashboard", [pathname]);
  const navigate = (href: string) => { window.history.pushState({}, "", href); setPathname(href); };
  useEffect(() => { setPathname(window.location.pathname); const listener = () => setPathname(window.location.pathname); window.addEventListener("popstate", listener); return () => window.removeEventListener("popstate", listener); }, []);
  useEffect(() => { setError(""); if (section === "dashboard") api<Dashboard>("dashboard").then(setDashboard).catch((e: Error) => setError(e.message)); if (section === "coloring-pages" || section === "product-links") Promise.all([api<Page[]>(`coloring-pages?q=${encodeURIComponent(query)}`), api<Taxonomy[]>("categories"), api<Taxonomy[]>("themes")]).then(([nextPages, nextCategories, nextThemes]) => { setPages(nextPages); setCategories(nextCategories); setThemes(nextThemes); }).catch((e: Error) => setError(e.message)); }, [section, query]);
  const bulk = async (action: string) => { if (!selected.length || (action === "delete" && !window.confirm(`Delete ${selected.length} selected coloring pages? This cannot be undone.`))) return; try { await api("coloring-pages/bulk", { method: "POST", body: JSON.stringify({ action, ids: selected }) }); setSelected([]); setPages(await api<Page[]>(`coloring-pages?q=${encodeURIComponent(query)}`)); } catch (e) { setError((e as Error).message); } };
  const relationship = async (action: string, targetId: string) => { try { await api("relationships", { method: "POST", body: JSON.stringify({ action, targetId, pageIds: selected }) }); setSelected([]); setPages(await api<Page[]>(`coloring-pages?q=${encodeURIComponent(query)}`)); } catch (e) { setError((e as Error).message); } };
  return <div className={styles.shell}><aside className={styles.sidebar}><strong>MythColoring Admin</strong><nav>{nav.map(([label, href]) => <a key={href} className={section === (href.split("/").filter(Boolean)[1] ?? "dashboard") ? styles.active : ""} href={href} onClick={(event) => { event.preventDefault(); navigate(href); }}>{label}</a>)}</nav><a className={styles.logout} href="/cdn-cgi/access/logout">Log out</a></aside><main className={styles.main}><header className={styles.topbar}><p>Secure content workspace</p><span>Cloudflare Access protected</span></header>{error && <p className={styles.error}>{error}</p>}{section === "dashboard" && <DashboardView data={dashboard} navigate={navigate} />}{section === "coloring-pages" && <PagesView pages={pages} categories={categories} themes={themes} query={query} setQuery={setQuery} selected={selected} setSelected={setSelected} bulk={bulk} relationship={relationship} />}{section === "product-links" && <ProductLinksView pages={pages} />}{["themes", "media", "seo", "settings"].includes(section) && <Placeholder section={section} />}</main></div>;
}
function DashboardView({ data, navigate }: { data: Dashboard | null; navigate: (href: string) => void }) { const labels = ["Total Coloring Pages", "Published", "Draft", "Hidden", "Total Themes", "Total Images", "Pages With Amazon Links", "Pages Missing Amazon Links"]; return <><div className={styles.heading}><div><p className="eyebrow">Dashboard</p><h1>Content overview</h1></div><button onClick={() => navigate("/rake/coloring-pages/")}>+ Add Coloring Page</button></div><div className={styles.stats}>{labels.map((label, index) => <article key={label}><span>{label}</span><strong>{data?.totals[index] ?? "—"}</strong></article>)}</div><section className={styles.panel}><h2>Recently Added</h2>{data?.recent.length ? data.recent.map((page) => <p key={page.id}>{page.title} <small>{page.status}</small></p>) : <p>No content has been imported into D1 yet.</p>}</section></>; }
function PagesView({ pages, categories, themes, query, setQuery, selected, setSelected, bulk, relationship }: { pages: Page[]; categories: Taxonomy[]; themes: Taxonomy[]; query: string; setQuery: (value: string) => void; selected: string[]; setSelected: (value: string[]) => void; bulk: (action: string) => void; relationship: (action: string, targetId: string) => void }) { const [categoryId, setCategoryId] = useState(""); const [themeId, setThemeId] = useState(""); const toggle = (id: string) => setSelected(selected.includes(id) ? selected.filter((value) => value !== id) : [...selected, id]); return <><div className={styles.heading}><div><p className="eyebrow">Coloring Pages</p><h1>Manage coloring pages</h1></div></div><input className={styles.search} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search title or slug" />{selected.length > 0 && <div className={styles.bulk}><b>{selected.length} selected</b><select value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">Choose category</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={!categoryId} onClick={() => relationship("set_category", categoryId)}>Assign Category</button><select value={themeId} onChange={(event) => setThemeId(event.target.value)}><option value="">Choose theme</option>{themes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button disabled={!themeId} onClick={() => relationship("assign_theme", themeId)}>Assign Theme</button><button disabled={!themeId} onClick={() => relationship("remove_theme", themeId)}>Remove Theme</button><button onClick={() => bulk("published")}>Publish</button><button onClick={() => bulk("draft")}>Set Draft</button><button onClick={() => bulk("hidden")}>Hide</button><button className={styles.danger} onClick={() => bulk("delete")}>Delete</button></div>}<div className={styles.list}>{pages.map((page) => <article key={page.id}><input type="checkbox" checked={selected.includes(page.id)} onChange={() => toggle(page.id)} />{page.thumbnail_url ? <img src={page.thumbnail_url} alt="" /> : <div className={styles.thumb}>No image</div>}<div><strong>{page.title}</strong><span>/{page.slug}</span><small>{page.categories || "Unassigned"} · {page.themes || "No themes"}</small></div><span className={styles.status}>{page.status}</span><small>{page.product_link_count ? "Amazon link" : "No Amazon link"}</small></article>)}{!pages.length && <p className={styles.empty}>No content found.</p>}</div></>; }
function ProductLinksView({ pages }: { pages: Page[] }) { const [links, setLinks] = useState<ProductLink[]>([]); const [pageId, setPageId] = useState(""); const [url, setUrl] = useState(""); const [message, setMessage] = useState(""); const refresh = () => api<ProductLink[]>("product-links").then(setLinks).catch((error: Error) => setMessage(error.message)); useEffect(() => { refresh(); }, []); const save = async () => { try { await api("product-links", { method: "POST", body: JSON.stringify({ pageId, platform: "amazon", market: "US", label: "Get This Artwork as a Poster", url }) }); setUrl(""); setMessage("Amazon link saved."); refresh(); } catch (error) { setMessage((error as Error).message); } }; const edit = async (link: ProductLink) => { const next = window.prompt("Amazon URL", link.url); if (!next || next === link.url) return; try { await api(`product-links/${link.id}`, { method: "PATCH", body: JSON.stringify({ pageId: link.page_id, platform: link.platform, market: link.market, label: "Get This Artwork as a Poster", url: next, enabled: Boolean(link.enabled) }) }); setMessage("Amazon link updated."); refresh(); } catch (error) { setMessage((error as Error).message); } }; return <><div className={styles.heading}><div><p className="eyebrow">Product Links</p><h1>Amazon links</h1></div></div><div className={styles.panel}><select value={pageId} onChange={(event) => setPageId(event.target.value)}><option value="">Choose coloring page</option>{pages.map((page) => <option key={page.id} value={page.id}>{page.title}</option>)}</select><input className={styles.search} value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://www.amazon.com/..." /><button disabled={!pageId || !url} onClick={save}>Save Amazon URL</button>{message && <p>{message}</p>}</div><div className={styles.list}>{links.map((link) => <article key={link.id}><div className={styles.thumb}>Amazon</div><div><strong>{link.title}</strong><span>{link.url}</span></div><span className={styles.status}>{link.enabled ? "Enabled" : "Disabled"}</span><button onClick={() => edit(link)}>Edit</button></article>)}</div></>; }
function Placeholder({ section }: { section: string }) { const names: Record<string, string> = { themes: "Themes", media: "Media Library", "product-links": "Product Links", seo: "SEO", settings: "Settings" }; return <div className={styles.panel}><p className="eyebrow">{names[section]}</p><h1>{names[section]}</h1><p>This protected module is ready for its D1-backed data after the approved content migration.</p></div>; }
