-- September object printables. Safe to re-run: stable source keys prevent
-- duplicate catalog records, and relationship inserts are idempotent.
PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO categories (id, name, slug, description, sort_order, status) VALUES
  ('cat-bags-travel', 'Bags & Travel', 'bags-travel', 'Handbags, satchels, suitcases, and other everyday travel accessories to color.', 30, 'published'),
  ('cat-road-safety', 'Road Safety', 'road-safety', 'Traffic signs, signals, and road-safety objects to color and explore.', 31, 'published');

INSERT OR IGNORE INTO coloring_pages (
  id, content_type, title, slug, short_description, line_art_url,
  color_reference_url, thumbnail_url, seo_title, meta_description,
  featured, status, sort_order, source_key
) VALUES
  ('page-object-tagged-handbag', 'standard', 'Tagged Handbag Coloring Page', 'tagged-handbag', 'A roomy handbag with a hanging tag and sturdy shoulder straps.', '/coloring-pages/objects/tagged-handbag/line-art.webp', '/coloring-pages/objects/tagged-handbag/color.webp', '/coloring-pages/objects/tagged-handbag/line-art.webp', 'Tagged Handbag Coloring Page – Free Printable', 'Download a free printable tagged handbag coloring page with clean line art and a color reference.', 1, 'published', 300, 'standard:objects:tagged-handbag'),
  ('page-object-leather-satchel', 'standard', 'Leather Satchel Coloring Page', 'leather-satchel', 'A classic flap satchel with buckles, a handle, and textured leather panels.', '/coloring-pages/objects/leather-satchel/line-art.webp', '/coloring-pages/objects/leather-satchel/color.webp', '/coloring-pages/objects/leather-satchel/line-art.webp', 'Leather Satchel Coloring Page – Free Printable', 'Download a free printable leather satchel coloring page with clean line art and a color reference.', 0, 'published', 301, 'standard:objects:leather-satchel'),
  ('page-object-travel-suitcase', 'standard', 'Travel Suitcase Coloring Page', 'travel-suitcase', 'A compact travel suitcase with reinforced corners, a handle, and a central clasp.', '/coloring-pages/objects/travel-suitcase/line-art.webp', '/coloring-pages/objects/travel-suitcase/color.webp', '/coloring-pages/objects/travel-suitcase/line-art.webp', 'Travel Suitcase Coloring Page – Free Printable', 'Download a free printable travel suitcase coloring page with clean line art and a color reference.', 0, 'published', 302, 'standard:objects:travel-suitcase'),
  ('page-object-leather-crossbody-bag', 'standard', 'Leather Crossbody Bag Coloring Page', 'leather-crossbody-bag', 'A detailed crossbody bag with a long strap, stitched panels, and a round clasp.', '/coloring-pages/objects/leather-crossbody-bag/line-art.webp', '/coloring-pages/objects/leather-crossbody-bag/color.webp', '/coloring-pages/objects/leather-crossbody-bag/line-art.webp', 'Leather Crossbody Bag Coloring Page – Free Printable', 'Download a free printable leather crossbody bag coloring page with clean line art and a color reference.', 0, 'published', 303, 'standard:objects:leather-crossbody-bag'),
  ('page-object-road-barricade', 'standard', 'Road Barricade Coloring Page', 'road-barricade', 'A striped road barricade with a warning light and folding support legs.', '/coloring-pages/objects/road-barricade/line-art.webp', '/coloring-pages/objects/road-barricade/color.webp', '/coloring-pages/objects/road-barricade/line-art.webp', 'Road Barricade Coloring Page – Free Printable', 'Download a free printable road barricade coloring page with clean line art and a color reference.', 1, 'published', 310, 'standard:objects:road-barricade'),
  ('page-object-merge-warning-signs', 'standard', 'Merge Warning Signs Coloring Page', 'merge-warning-signs', 'A pair of warning road signs showing lane-merging symbols.', '/coloring-pages/objects/merge-warning-signs/line-art.webp', '/coloring-pages/objects/merge-warning-signs/color.webp', '/coloring-pages/objects/merge-warning-signs/line-art.webp', 'Merge Warning Signs Coloring Page – Free Printable', 'Download a free printable merge warning signs coloring page with clean line art and a color reference.', 0, 'published', 311, 'standard:objects:merge-warning-signs'),
  ('page-object-stop-sign-and-cone', 'standard', 'Stop Sign and Traffic Cone Coloring Page', 'stop-sign-and-cone', 'A familiar stop sign standing beside a striped safety cone.', '/coloring-pages/objects/stop-sign-and-cone/line-art.webp', '/coloring-pages/objects/stop-sign-and-cone/color.webp', '/coloring-pages/objects/stop-sign-and-cone/line-art.webp', 'Stop Sign and Traffic Cone Coloring Page – Free Printable', 'Download a free printable stop sign and traffic cone coloring page with clean line art and a color reference.', 0, 'published', 312, 'standard:objects:stop-sign-and-cone'),
  ('page-object-sandbag-barrier', 'standard', 'Sandbag Barrier Coloring Page', 'sandbag-barrier', 'A sturdy filled sandbag used as a temporary safety barrier.', '/coloring-pages/objects/sandbag-barrier/line-art.webp', '/coloring-pages/objects/sandbag-barrier/color.webp', '/coloring-pages/objects/sandbag-barrier/line-art.webp', 'Sandbag Barrier Coloring Page – Free Printable', 'Download a free printable sandbag barrier coloring page with clean line art and a color reference.', 0, 'published', 313, 'standard:objects:sandbag-barrier'),
  ('page-object-parking-sign', 'standard', 'Parking Sign Coloring Page', 'parking-sign', 'A round parking sign on a tall post with a directional arrow.', '/coloring-pages/objects/parking-sign/line-art.webp', '/coloring-pages/objects/parking-sign/color.webp', '/coloring-pages/objects/parking-sign/line-art.webp', 'Parking Sign Coloring Page – Free Printable', 'Download a free printable parking sign coloring page with clean line art and a color reference.', 0, 'published', 314, 'standard:objects:parking-sign'),
  ('page-object-wooden-direction-sign', 'standard', 'Wooden Direction Sign Coloring Page', 'wooden-direction-sign', 'A weathered wooden signpost with arrows pointing in different directions.', '/coloring-pages/objects/wooden-direction-sign/line-art.webp', '/coloring-pages/objects/wooden-direction-sign/color.webp', '/coloring-pages/objects/wooden-direction-sign/line-art.webp', 'Wooden Direction Sign Coloring Page – Free Printable', 'Download a free printable wooden direction sign coloring page with clean line art and a color reference.', 0, 'published', 315, 'standard:objects:wooden-direction-sign'),
  ('page-object-weather-vane', 'standard', 'Weather Vane Coloring Page', 'weather-vane', 'A compass-style weather vane with cardinal direction letters and an arrow.', '/coloring-pages/objects/weather-vane/line-art.webp', '/coloring-pages/objects/weather-vane/color.webp', '/coloring-pages/objects/weather-vane/line-art.webp', 'Weather Vane Coloring Page – Free Printable', 'Download a free printable weather vane coloring page with clean line art and a color reference.', 0, 'published', 316, 'standard:objects:weather-vane'),
  ('page-object-right-turn-sign', 'standard', 'Right Turn Sign Coloring Page', 'right-turn-sign', 'A diamond-shaped road sign with a bold right-turn arrow.', '/coloring-pages/objects/right-turn-sign/line-art.webp', '/coloring-pages/objects/right-turn-sign/color.webp', '/coloring-pages/objects/right-turn-sign/line-art.webp', 'Right Turn Sign Coloring Page – Free Printable', 'Download a free printable right turn sign coloring page with clean line art and a color reference.', 0, 'published', 317, 'standard:objects:right-turn-sign'),
  ('page-object-steering-wheel', 'standard', 'Steering Wheel Coloring Page', 'steering-wheel', 'A detailed steering wheel with padded grips and a central horn button.', '/coloring-pages/objects/steering-wheel/line-art.webp', '/coloring-pages/objects/steering-wheel/color.webp', '/coloring-pages/objects/steering-wheel/line-art.webp', 'Steering Wheel Coloring Page – Free Printable', 'Download a free printable steering wheel coloring page with clean line art and a color reference.', 0, 'published', 318, 'standard:objects:steering-wheel'),
  ('page-object-vehicle-horn', 'standard', 'Vehicle Horn Coloring Page', 'vehicle-horn', 'A classic vehicle horn with a flared speaker and sturdy base.', '/coloring-pages/objects/vehicle-horn/line-art.webp', '/coloring-pages/objects/vehicle-horn/color.webp', '/coloring-pages/objects/vehicle-horn/line-art.webp', 'Vehicle Horn Coloring Page – Free Printable', 'Download a free printable vehicle horn coloring page with clean line art and a color reference.', 0, 'published', 319, 'standard:objects:vehicle-horn'),
  ('page-object-traffic-light', 'standard', 'Traffic Light Coloring Page', 'traffic-light', 'A three-color traffic signal with red, amber, and green lenses.', '/coloring-pages/objects/traffic-light/line-art.webp', '/coloring-pages/objects/traffic-light/color.webp', '/coloring-pages/objects/traffic-light/line-art.webp', 'Traffic Light Coloring Page – Free Printable', 'Download a free printable traffic light coloring page with clean line art and a color reference.', 0, 'published', 320, 'standard:objects:traffic-light'),
  ('page-object-roadside-billboard', 'standard', 'Roadside Billboard Coloring Page', 'roadside-billboard', 'A blank roadside billboard ready for an original message or design.', '/coloring-pages/objects/roadside-billboard/line-art.webp', '/coloring-pages/objects/roadside-billboard/color.webp', '/coloring-pages/objects/roadside-billboard/line-art.webp', 'Roadside Billboard Coloring Page – Free Printable', 'Download a free printable roadside billboard coloring page with clean line art and a color reference.', 0, 'published', 321, 'standard:objects:roadside-billboard'),
  ('page-object-intersection-warning-sign', 'standard', 'Intersection Warning Sign Coloring Page', 'intersection-warning-sign', 'A road warning sign showing a four-way intersection ahead.', '/coloring-pages/objects/intersection-warning-sign/line-art.webp', '/coloring-pages/objects/intersection-warning-sign/color.webp', '/coloring-pages/objects/intersection-warning-sign/line-art.webp', 'Intersection Warning Sign Coloring Page – Free Printable', 'Download a free printable intersection warning sign coloring page with clean line art and a color reference.', 0, 'published', 322, 'standard:objects:intersection-warning-sign'),
  ('page-object-crossed-road-tools', 'standard', 'Crossed Road Tools Coloring Page', 'crossed-road-tools', 'A shovel and hoe crossed in front of a work-zone sign.', '/coloring-pages/objects/crossed-road-tools/line-art.webp', '/coloring-pages/objects/crossed-road-tools/color.webp', '/coloring-pages/objects/crossed-road-tools/line-art.webp', 'Crossed Road Tools Coloring Page – Free Printable', 'Download a free printable crossed road tools coloring page with clean line art and a color reference.', 0, 'published', 323, 'standard:objects:crossed-road-tools'),
  ('page-object-traffic-cone', 'standard', 'Traffic Cone Coloring Page', 'traffic-cone', 'A striped traffic cone on a wide square base.', '/coloring-pages/objects/traffic-cone/line-art.webp', '/coloring-pages/objects/traffic-cone/color.webp', '/coloring-pages/objects/traffic-cone/line-art.webp', 'Traffic Cone Coloring Page – Free Printable', 'Download a free printable traffic cone coloring page with clean line art and a color reference.', 0, 'published', 324, 'standard:objects:traffic-cone'),
  ('page-object-rubber-mallet', 'standard', 'Rubber Mallet Coloring Page', 'rubber-mallet', 'A sturdy rubber mallet with a long wooden handle.', '/coloring-pages/objects/rubber-mallet/line-art.webp', '/coloring-pages/objects/rubber-mallet/color.webp', '/coloring-pages/objects/rubber-mallet/line-art.webp', 'Rubber Mallet Coloring Page – Free Printable', 'Download a free printable rubber mallet coloring page with clean line art and a color reference.', 0, 'published', 325, 'standard:objects:rubber-mallet'),
  ('page-object-blank-road-sign', 'standard', 'Blank Road Sign Coloring Page', 'blank-road-sign', 'An empty road sign panel that invites children to invent their own symbol.', '/coloring-pages/objects/blank-road-sign/line-art.webp', '/coloring-pages/objects/blank-road-sign/color.webp', '/coloring-pages/objects/blank-road-sign/line-art.webp', 'Blank Road Sign Coloring Page – Free Printable', 'Download a free printable blank road sign coloring page with clean line art and a color reference.', 0, 'published', 326, 'standard:objects:blank-road-sign'),
  ('page-object-traffic-delineator', 'standard', 'Traffic Delineator Coloring Page', 'traffic-delineator', 'A tall reflective traffic delineator with round safety lenses.', '/coloring-pages/objects/traffic-delineator/line-art.webp', '/coloring-pages/objects/traffic-delineator/color.webp', '/coloring-pages/objects/traffic-delineator/line-art.webp', 'Traffic Delineator Coloring Page – Free Printable', 'Download a free printable traffic delineator coloring page with clean line art and a color reference.', 0, 'published', 327, 'standard:objects:traffic-delineator');

INSERT OR IGNORE INTO page_categories (page_id, category_id, is_primary)
SELECT id, 'cat-bags-travel', 1 FROM coloring_pages WHERE source_key LIKE 'standard:objects:%' AND slug IN ('tagged-handbag', 'leather-satchel', 'travel-suitcase', 'leather-crossbody-bag');

INSERT OR IGNORE INTO page_categories (page_id, category_id, is_primary)
SELECT id, 'cat-road-safety', 1 FROM coloring_pages WHERE source_key LIKE 'standard:objects:%' AND slug NOT IN ('tagged-handbag', 'leather-satchel', 'travel-suitcase', 'leather-crossbody-bag');
