-- September anime and character-art printables. This migration is safe to
-- re-run because it uses stable IDs, source keys, and idempotent inserts.
PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO categories (id, name, slug, description, sort_order, status)
VALUES ('cat-anime-character-art', 'Anime & Character Art', 'anime-character-art', 'Anime-style characters, costumes, and expressive portraits ready to color.', 32, 'published');

INSERT OR IGNORE INTO coloring_pages (
  id, content_type, title, slug, short_description, line_art_url,
  color_reference_url, thumbnail_url, featured, status, sort_order, source_key
) VALUES
  ('page-anime-blue-uniform-swordsman', 'standard', 'Blue Uniform Swordsman Coloring Page', 'blue-uniform-swordsman', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/blue-uniform-swordsman/line-art.webp', '/coloring-pages/anime-characters/blue-uniform-swordsman/color.webp', '/coloring-pages/anime-characters/blue-uniform-swordsman/line-art.webp', 1, 'published', 400, 'standard:anime:blue-uniform-swordsman'),
  ('page-anime-girl-with-parasol', 'standard', 'Girl with Parasol Coloring Page', 'girl-with-parasol', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/girl-with-parasol/line-art.webp', '/coloring-pages/anime-characters/girl-with-parasol/color.webp', '/coloring-pages/anime-characters/girl-with-parasol/line-art.webp', 1, 'published', 401, 'standard:anime:girl-with-parasol'),
  ('page-anime-pink-haired-cat-girl', 'standard', 'Pink-Haired Cat Girl Coloring Page', 'pink-haired-cat-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/pink-haired-cat-girl/line-art.webp', '/coloring-pages/anime-characters/pink-haired-cat-girl/color.webp', '/coloring-pages/anime-characters/pink-haired-cat-girl/line-art.webp', 1, 'published', 402, 'standard:anime:pink-haired-cat-girl'),
  ('page-anime-pink-bow-girl', 'standard', 'Pink Bow Girl Coloring Page', 'pink-bow-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/pink-bow-girl/line-art.webp', '/coloring-pages/anime-characters/pink-bow-girl/color.webp', '/coloring-pages/anime-characters/pink-bow-girl/line-art.webp', 1, 'published', 403, 'standard:anime:pink-bow-girl'),
  ('page-anime-school-blazer-girl', 'standard', 'School Blazer Girl Coloring Page', 'school-blazer-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/school-blazer-girl/line-art.webp', '/coloring-pages/anime-characters/school-blazer-girl/color.webp', '/coloring-pages/anime-characters/school-blazer-girl/line-art.webp', 0, 'published', 404, 'standard:anime:school-blazer-girl'),
  ('page-anime-martial-artist', 'standard', 'Martial Artist Coloring Page', 'martial-artist', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/martial-artist/line-art.webp', '/coloring-pages/anime-characters/martial-artist/color.webp', '/coloring-pages/anime-characters/martial-artist/line-art.webp', 0, 'published', 405, 'standard:anime:martial-artist'),
  ('page-anime-blue-suit-boy', 'standard', 'Blue Suit Boy Coloring Page', 'blue-suit-boy', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/blue-suit-boy/line-art.webp', '/coloring-pages/anime-characters/blue-suit-boy/color.webp', '/coloring-pages/anime-characters/blue-suit-boy/line-art.webp', 0, 'published', 406, 'standard:anime:blue-suit-boy'),
  ('page-anime-garden-archer', 'standard', 'Garden Archer Coloring Page', 'garden-archer', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/garden-archer/line-art.webp', '/coloring-pages/anime-characters/garden-archer/color.webp', '/coloring-pages/anime-characters/garden-archer/line-art.webp', 0, 'published', 407, 'standard:anime:garden-archer'),
  ('page-anime-red-dress-girl', 'standard', 'Red Dress Girl Coloring Page', 'red-dress-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/red-dress-girl/line-art.webp', '/coloring-pages/anime-characters/red-dress-girl/color.webp', '/coloring-pages/anime-characters/red-dress-girl/line-art.webp', 0, 'published', 408, 'standard:anime:red-dress-girl'),
  ('page-anime-resting-girl', 'standard', 'Resting Girl Coloring Page', 'resting-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/resting-girl/line-art.webp', '/coloring-pages/anime-characters/resting-girl/color.webp', '/coloring-pages/anime-characters/resting-girl/line-art.webp', 0, 'published', 409, 'standard:anime:resting-girl'),
  ('page-anime-fantasy-warrior', 'standard', 'Fantasy Warrior Coloring Page', 'fantasy-warrior', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/fantasy-warrior/line-art.webp', '/coloring-pages/anime-characters/fantasy-warrior/color.webp', '/coloring-pages/anime-characters/fantasy-warrior/line-art.webp', 0, 'published', 410, 'standard:anime:fantasy-warrior'),
  ('page-anime-blue-coat-girl', 'standard', 'Blue Coat Girl Coloring Page', 'blue-coat-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/blue-coat-girl/line-art.webp', '/coloring-pages/anime-characters/blue-coat-girl/color.webp', '/coloring-pages/anime-characters/blue-coat-girl/line-art.webp', 0, 'published', 411, 'standard:anime:blue-coat-girl'),
  ('page-anime-standing-girl', 'standard', 'Standing Girl Coloring Page', 'standing-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/standing-girl/line-art.webp', '/coloring-pages/anime-characters/standing-girl/color.webp', '/coloring-pages/anime-characters/standing-girl/line-art.webp', 0, 'published', 412, 'standard:anime:standing-girl'),
  ('page-anime-scarf-girl', 'standard', 'Scarf Girl Coloring Page', 'scarf-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/scarf-girl/line-art.webp', '/coloring-pages/anime-characters/scarf-girl/color.webp', '/coloring-pages/anime-characters/scarf-girl/line-art.webp', 0, 'published', 413, 'standard:anime:scarf-girl'),
  ('page-anime-armored-heroine', 'standard', 'Armored Heroine Coloring Page', 'armored-heroine', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/armored-heroine/line-art.webp', '/coloring-pages/anime-characters/armored-heroine/color.webp', '/coloring-pages/anime-characters/armored-heroine/line-art.webp', 0, 'published', 414, 'standard:anime:armored-heroine'),
  ('page-anime-long-haired-girl', 'standard', 'Long-Haired Girl Coloring Page', 'long-haired-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/long-haired-girl/line-art.webp', '/coloring-pages/anime-characters/long-haired-girl/color.webp', '/coloring-pages/anime-characters/long-haired-girl/line-art.webp', 0, 'published', 415, 'standard:anime:long-haired-girl'),
  ('page-anime-seated-swordsman', 'standard', 'Seated Swordsman Coloring Page', 'seated-swordsman', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/seated-swordsman/line-art.webp', '/coloring-pages/anime-characters/seated-swordsman/color.webp', '/coloring-pages/anime-characters/seated-swordsman/line-art.webp', 0, 'published', 416, 'standard:anime:seated-swordsman'),
  ('page-anime-kimono-swordsman', 'standard', 'Kimono Swordsman Coloring Page', 'kimono-swordsman', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/kimono-swordsman/line-art.webp', '/coloring-pages/anime-characters/kimono-swordsman/color.webp', '/coloring-pages/anime-characters/kimono-swordsman/line-art.webp', 0, 'published', 417, 'standard:anime:kimono-swordsman'),
  ('page-anime-sailor-uniform-girl', 'standard', 'Sailor Uniform Girl Coloring Page', 'sailor-uniform-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/sailor-uniform-girl/line-art.webp', '/coloring-pages/anime-characters/sailor-uniform-girl/color.webp', '/coloring-pages/anime-characters/sailor-uniform-girl/line-art.webp', 0, 'published', 418, 'standard:anime:sailor-uniform-girl'),
  ('page-anime-bow-tie-girl', 'standard', 'Bow Tie Girl Coloring Page', 'bow-tie-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/bow-tie-girl/line-art.webp', '/coloring-pages/anime-characters/bow-tie-girl/color.webp', '/coloring-pages/anime-characters/bow-tie-girl/line-art.webp', 0, 'published', 419, 'standard:anime:bow-tie-girl'),
  ('page-anime-three-friends', 'standard', 'Three Friends Coloring Page', 'three-friends', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/three-friends/line-art.webp', '/coloring-pages/anime-characters/three-friends/color.webp', '/coloring-pages/anime-characters/three-friends/line-art.webp', 0, 'published', 420, 'standard:anime:three-friends'),
  ('page-anime-kimono-portrait', 'standard', 'Kimono Portrait Coloring Page', 'kimono-portrait', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/kimono-portrait/line-art.webp', '/coloring-pages/anime-characters/kimono-portrait/color.webp', '/coloring-pages/anime-characters/kimono-portrait/line-art.webp', 0, 'published', 421, 'standard:anime:kimono-portrait'),
  ('page-anime-cloaked-hero', 'standard', 'Cloaked Hero Coloring Page', 'cloaked-hero', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/cloaked-hero/line-art.webp', '/coloring-pages/anime-characters/cloaked-hero/color.webp', '/coloring-pages/anime-characters/cloaked-hero/line-art.webp', 0, 'published', 422, 'standard:anime:cloaked-hero'),
  ('page-anime-ribbon-dress-girl', 'standard', 'Ribbon Dress Girl Coloring Page', 'ribbon-dress-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/ribbon-dress-girl/line-art.webp', '/coloring-pages/anime-characters/ribbon-dress-girl/color.webp', '/coloring-pages/anime-characters/ribbon-dress-girl/line-art.webp', 0, 'published', 423, 'standard:anime:ribbon-dress-girl'),
  ('page-anime-samurai-warrior', 'standard', 'Samurai Warrior Coloring Page', 'samurai-warrior', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/samurai-warrior/line-art.webp', '/coloring-pages/anime-characters/samurai-warrior/color.webp', '/coloring-pages/anime-characters/samurai-warrior/line-art.webp', 0, 'published', 424, 'standard:anime:samurai-warrior'),
  ('page-anime-violin-cat-girl', 'standard', 'Violin Cat Girl Coloring Page', 'violin-cat-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/violin-cat-girl/line-art.webp', '/coloring-pages/anime-characters/violin-cat-girl/color.webp', '/coloring-pages/anime-characters/violin-cat-girl/line-art.webp', 0, 'published', 425, 'standard:anime:violin-cat-girl'),
  ('page-anime-winter-scarf-girl', 'standard', 'Winter Scarf Girl Coloring Page', 'winter-scarf-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/winter-scarf-girl/line-art.webp', '/coloring-pages/anime-characters/winter-scarf-girl/color.webp', '/coloring-pages/anime-characters/winter-scarf-girl/line-art.webp', 0, 'published', 426, 'standard:anime:winter-scarf-girl'),
  ('page-anime-long-coat-hero', 'standard', 'Long Coat Hero Coloring Page', 'long-coat-hero', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/long-coat-hero/line-art.webp', '/coloring-pages/anime-characters/long-coat-hero/color.webp', '/coloring-pages/anime-characters/long-coat-hero/line-art.webp', 0, 'published', 427, 'standard:anime:long-coat-hero'),
  ('page-anime-magic-orb-hero', 'standard', 'Magic Orb Hero Coloring Page', 'magic-orb-hero', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/magic-orb-hero/line-art.webp', '/coloring-pages/anime-characters/magic-orb-hero/color.webp', '/coloring-pages/anime-characters/magic-orb-hero/line-art.webp', 0, 'published', 428, 'standard:anime:magic-orb-hero'),
  ('page-anime-tree-guardian', 'standard', 'Tree Guardian Coloring Page', 'tree-guardian', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/tree-guardian/line-art.webp', '/coloring-pages/anime-characters/tree-guardian/color.webp', '/coloring-pages/anime-characters/tree-guardian/line-art.webp', 0, 'published', 429, 'standard:anime:tree-guardian'),
  ('page-anime-book-reading-mage', 'standard', 'Book-Reading Mage Coloring Page', 'book-reading-mage', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/book-reading-mage/line-art.webp', '/coloring-pages/anime-characters/book-reading-mage/color.webp', '/coloring-pages/anime-characters/book-reading-mage/line-art.webp', 0, 'published', 430, 'standard:anime:book-reading-mage'),
  ('page-anime-violin-player', 'standard', 'Violin Player Coloring Page', 'violin-player', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/violin-player/line-art.webp', '/coloring-pages/anime-characters/violin-player/color.webp', '/coloring-pages/anime-characters/violin-player/line-art.webp', 0, 'published', 431, 'standard:anime:violin-player'),
  ('page-anime-winter-letter-girl', 'standard', 'Winter Letter Girl Coloring Page', 'winter-letter-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/winter-letter-girl/line-art.webp', '/coloring-pages/anime-characters/winter-letter-girl/color.webp', '/coloring-pages/anime-characters/winter-letter-girl/line-art.webp', 0, 'published', 432, 'standard:anime:winter-letter-girl'),
  ('page-anime-pumpkin-guitarist', 'standard', 'Pumpkin Guitarist Coloring Page', 'pumpkin-guitarist', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/pumpkin-guitarist/line-art.webp', '/coloring-pages/anime-characters/pumpkin-guitarist/color.webp', '/coloring-pages/anime-characters/pumpkin-guitarist/line-art.webp', 0, 'published', 433, 'standard:anime:pumpkin-guitarist'),
  ('page-anime-red-coat-hero', 'standard', 'Red Coat Hero Coloring Page', 'red-coat-hero', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/red-coat-hero/line-art.webp', '/coloring-pages/anime-characters/red-coat-hero/color.webp', '/coloring-pages/anime-characters/red-coat-hero/line-art.webp', 0, 'published', 434, 'standard:anime:red-coat-hero'),
  ('page-anime-red-hoodie-boy', 'standard', 'Red Hoodie Boy Coloring Page', 'red-hoodie-boy', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/red-hoodie-boy/line-art.webp', '/coloring-pages/anime-characters/red-hoodie-boy/color.webp', '/coloring-pages/anime-characters/red-hoodie-boy/line-art.webp', 0, 'published', 435, 'standard:anime:red-hoodie-boy'),
  ('page-anime-schoolgirl-with-satchel', 'standard', 'Schoolgirl with Satchel Coloring Page', 'schoolgirl-with-satchel', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/schoolgirl-with-satchel/line-art.webp', '/coloring-pages/anime-characters/schoolgirl-with-satchel/color.webp', '/coloring-pages/anime-characters/schoolgirl-with-satchel/line-art.webp', 0, 'published', 436, 'standard:anime:schoolgirl-with-satchel'),
  ('page-anime-caged-fantasy-girl', 'standard', 'Caged Fantasy Girl Coloring Page', 'caged-fantasy-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/caged-fantasy-girl/line-art.webp', '/coloring-pages/anime-characters/caged-fantasy-girl/color.webp', '/coloring-pages/anime-characters/caged-fantasy-girl/line-art.webp', 0, 'published', 437, 'standard:anime:caged-fantasy-girl'),
  ('page-anime-sports-action-collage', 'standard', 'Sports Action Collage Coloring Page', 'sports-action-collage', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/sports-action-collage/line-art.webp', '/coloring-pages/anime-characters/sports-action-collage/color.webp', '/coloring-pages/anime-characters/sports-action-collage/line-art.webp', 0, 'published', 438, 'standard:anime:sports-action-collage'),
  ('page-anime-witch-hat-girl', 'standard', 'Witch Hat Girl Coloring Page', 'witch-hat-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/witch-hat-girl/line-art.webp', '/coloring-pages/anime-characters/witch-hat-girl/color.webp', '/coloring-pages/anime-characters/witch-hat-girl/line-art.webp', 0, 'published', 439, 'standard:anime:witch-hat-girl'),
  ('page-anime-flower-hair-portrait', 'standard', 'Flower Hair Portrait Coloring Page', 'flower-hair-portrait', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/flower-hair-portrait/line-art.webp', '/coloring-pages/anime-characters/flower-hair-portrait/color.webp', '/coloring-pages/anime-characters/flower-hair-portrait/line-art.webp', 0, 'published', 440, 'standard:anime:flower-hair-portrait'),
  ('page-anime-costumed-girl', 'standard', 'Costumed Girl Coloring Page', 'costumed-girl', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/costumed-girl/line-art.webp', '/coloring-pages/anime-characters/costumed-girl/color.webp', '/coloring-pages/anime-characters/costumed-girl/line-art.webp', 0, 'published', 441, 'standard:anime:costumed-girl'),
  ('page-anime-sailor-uniform-portrait', 'standard', 'Sailor Uniform Portrait Coloring Page', 'sailor-uniform-portrait', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/sailor-uniform-portrait/line-art.webp', '/coloring-pages/anime-characters/sailor-uniform-portrait/color.webp', '/coloring-pages/anime-characters/sailor-uniform-portrait/line-art.webp', 0, 'published', 442, 'standard:anime:sailor-uniform-portrait'),
  ('page-anime-winter-sports-boy', 'standard', 'Winter Sports Boy Coloring Page', 'winter-sports-boy', 'Anime-style character illustration with detailed clothing and expressive features.', '/coloring-pages/anime-characters/winter-sports-boy/line-art.webp', '/coloring-pages/anime-characters/winter-sports-boy/color.webp', '/coloring-pages/anime-characters/winter-sports-boy/line-art.webp', 0, 'published', 443, 'standard:anime:winter-sports-boy');

INSERT OR IGNORE INTO page_categories (page_id, category_id, is_primary)
SELECT id, 'cat-anime-character-art', 1
FROM coloring_pages
WHERE source_key LIKE 'standard:anime:%';
