-- September architecture and landscape printables; safe to re-run.
PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO categories (id, name, slug, description, sort_order, status)
VALUES ('cat-architecture-landscapes', 'Architecture & Landscapes', 'architecture-landscapes', 'Homes, gardens, city scenes, and beautiful natural places to color.', 33, 'published');

INSERT OR IGNORE INTO coloring_pages (
  id, content_type, title, slug, short_description, line_art_url,
  color_reference_url, thumbnail_url, featured, status, sort_order, source_key
) VALUES
  ('page-places-garden-plan', 'standard', 'Garden Plan Coloring Page', 'garden-plan', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/garden-plan/line-art.webp', '/coloring-pages/architecture-landscapes/garden-plan/color.webp', '/coloring-pages/architecture-landscapes/garden-plan/line-art.webp', 1, 'published', 500, 'standard:places:garden-plan'),
  ('page-places-courtyard-garden-plan', 'standard', 'Courtyard Garden Plan Coloring Page', 'courtyard-garden-plan', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/courtyard-garden-plan/line-art.webp', '/coloring-pages/architecture-landscapes/courtyard-garden-plan/color.webp', '/coloring-pages/architecture-landscapes/courtyard-garden-plan/line-art.webp', 1, 'published', 501, 'standard:places:courtyard-garden-plan'),
  ('page-places-flowering-rock-garden', 'standard', 'Flowering Rock Garden Coloring Page', 'flowering-rock-garden', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/flowering-rock-garden/line-art.webp', '/coloring-pages/architecture-landscapes/flowering-rock-garden/color.webp', '/coloring-pages/architecture-landscapes/flowering-rock-garden/line-art.webp', 1, 'published', 502, 'standard:places:flowering-rock-garden'),
  ('page-places-garden-sunflower', 'standard', 'Garden Sunflower Coloring Page', 'garden-sunflower', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/garden-sunflower/line-art.webp', '/coloring-pages/architecture-landscapes/garden-sunflower/color.webp', '/coloring-pages/architecture-landscapes/garden-sunflower/line-art.webp', 1, 'published', 503, 'standard:places:garden-sunflower'),
  ('page-places-banana-plant', 'standard', 'Banana Plant Coloring Page', 'banana-plant', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/banana-plant/line-art.webp', '/coloring-pages/architecture-landscapes/banana-plant/color.webp', '/coloring-pages/architecture-landscapes/banana-plant/line-art.webp', 0, 'published', 504, 'standard:places:banana-plant'),
  ('page-places-palm-tree', 'standard', 'Palm Tree Coloring Page', 'palm-tree', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/palm-tree/line-art.webp', '/coloring-pages/architecture-landscapes/palm-tree/color.webp', '/coloring-pages/architecture-landscapes/palm-tree/line-art.webp', 0, 'published', 505, 'standard:places:palm-tree'),
  ('page-places-bamboo-grove', 'standard', 'Bamboo Grove Coloring Page', 'bamboo-grove', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/bamboo-grove/line-art.webp', '/coloring-pages/architecture-landscapes/bamboo-grove/color.webp', '/coloring-pages/architecture-landscapes/bamboo-grove/line-art.webp', 0, 'published', 506, 'standard:places:bamboo-grove'),
  ('page-places-tropical-modern-house', 'standard', 'Tropical Modern House Coloring Page', 'tropical-modern-house', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/tropical-modern-house/line-art.webp', '/coloring-pages/architecture-landscapes/tropical-modern-house/color.webp', '/coloring-pages/architecture-landscapes/tropical-modern-house/line-art.webp', 0, 'published', 507, 'standard:places:tropical-modern-house'),
  ('page-places-hillside-wooden-house', 'standard', 'Hillside Wooden House Coloring Page', 'hillside-wooden-house', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/hillside-wooden-house/line-art.webp', '/coloring-pages/architecture-landscapes/hillside-wooden-house/color.webp', '/coloring-pages/architecture-landscapes/hillside-wooden-house/line-art.webp', 0, 'published', 508, 'standard:places:hillside-wooden-house'),
  ('page-places-tropical-riverside', 'standard', 'Tropical Riverside Coloring Page', 'tropical-riverside', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/tropical-riverside/line-art.webp', '/coloring-pages/architecture-landscapes/tropical-riverside/color.webp', '/coloring-pages/architecture-landscapes/tropical-riverside/line-art.webp', 0, 'published', 509, 'standard:places:tropical-riverside'),
  ('page-places-seaside-boardwalk', 'standard', 'Seaside Boardwalk Coloring Page', 'seaside-boardwalk', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/seaside-boardwalk/line-art.webp', '/coloring-pages/architecture-landscapes/seaside-boardwalk/color.webp', '/coloring-pages/architecture-landscapes/seaside-boardwalk/line-art.webp', 0, 'published', 510, 'standard:places:seaside-boardwalk'),
  ('page-places-garden-gazebo', 'standard', 'Garden Gazebo Coloring Page', 'garden-gazebo', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/garden-gazebo/line-art.webp', '/coloring-pages/architecture-landscapes/garden-gazebo/color.webp', '/coloring-pages/architecture-landscapes/garden-gazebo/line-art.webp', 0, 'published', 511, 'standard:places:garden-gazebo'),
  ('page-places-historic-streetscape', 'standard', 'Historic Streetscape Coloring Page', 'historic-streetscape', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/historic-streetscape/line-art.webp', '/coloring-pages/architecture-landscapes/historic-streetscape/color.webp', '/coloring-pages/architecture-landscapes/historic-streetscape/line-art.webp', 0, 'published', 512, 'standard:places:historic-streetscape'),
  ('page-places-tropical-decorative-gate', 'standard', 'Tropical Decorative Gate Coloring Page', 'tropical-decorative-gate', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/tropical-decorative-gate/line-art.webp', '/coloring-pages/architecture-landscapes/tropical-decorative-gate/color.webp', '/coloring-pages/architecture-landscapes/tropical-decorative-gate/line-art.webp', 0, 'published', 513, 'standard:places:tropical-decorative-gate'),
  ('page-places-layered-garden', 'standard', 'Layered Garden Coloring Page', 'layered-garden', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/layered-garden/line-art.webp', '/coloring-pages/architecture-landscapes/layered-garden/color.webp', '/coloring-pages/architecture-landscapes/layered-garden/line-art.webp', 0, 'published', 514, 'standard:places:layered-garden'),
  ('page-places-modern-garden-terrace', 'standard', 'Modern Garden Terrace Coloring Page', 'modern-garden-terrace', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/modern-garden-terrace/line-art.webp', '/coloring-pages/architecture-landscapes/modern-garden-terrace/color.webp', '/coloring-pages/architecture-landscapes/modern-garden-terrace/line-art.webp', 0, 'published', 515, 'standard:places:modern-garden-terrace'),
  ('page-places-tropical-water-garden', 'standard', 'Tropical Water Garden Coloring Page', 'tropical-water-garden', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/tropical-water-garden/line-art.webp', '/coloring-pages/architecture-landscapes/tropical-water-garden/color.webp', '/coloring-pages/architecture-landscapes/tropical-water-garden/line-art.webp', 0, 'published', 516, 'standard:places:tropical-water-garden'),
  ('page-places-stone-stair-path', 'standard', 'Stone Stair Path Coloring Page', 'stone-stair-path', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/stone-stair-path/line-art.webp', '/coloring-pages/architecture-landscapes/stone-stair-path/color.webp', '/coloring-pages/architecture-landscapes/stone-stair-path/line-art.webp', 0, 'published', 517, 'standard:places:stone-stair-path'),
  ('page-places-lakeside-house', 'standard', 'Lakeside House Coloring Page', 'lakeside-house', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/lakeside-house/line-art.webp', '/coloring-pages/architecture-landscapes/lakeside-house/color.webp', '/coloring-pages/architecture-landscapes/lakeside-house/line-art.webp', 0, 'published', 518, 'standard:places:lakeside-house'),
  ('page-places-woodland-cabin', 'standard', 'Woodland Cabin Coloring Page', 'woodland-cabin', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/woodland-cabin/line-art.webp', '/coloring-pages/architecture-landscapes/woodland-cabin/color.webp', '/coloring-pages/architecture-landscapes/woodland-cabin/line-art.webp', 0, 'published', 519, 'standard:places:woodland-cabin'),
  ('page-places-young-tree', 'standard', 'Young Tree Coloring Page', 'young-tree', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/young-tree/line-art.webp', '/coloring-pages/architecture-landscapes/young-tree/color.webp', '/coloring-pages/architecture-landscapes/young-tree/line-art.webp', 0, 'published', 520, 'standard:places:young-tree'),
  ('page-places-hillside-stilt-house', 'standard', 'Hillside Stilt House Coloring Page', 'hillside-stilt-house', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/hillside-stilt-house/line-art.webp', '/coloring-pages/architecture-landscapes/hillside-stilt-house/color.webp', '/coloring-pages/architecture-landscapes/hillside-stilt-house/line-art.webp', 0, 'published', 521, 'standard:places:hillside-stilt-house'),
  ('page-places-hillside-village', 'standard', 'Hillside Village Coloring Page', 'hillside-village', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/hillside-village/line-art.webp', '/coloring-pages/architecture-landscapes/hillside-village/color.webp', '/coloring-pages/architecture-landscapes/hillside-village/line-art.webp', 0, 'published', 522, 'standard:places:hillside-village'),
  ('page-places-hexagonal-boardwalk', 'standard', 'Hexagonal Boardwalk Coloring Page', 'hexagonal-boardwalk', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/hexagonal-boardwalk/line-art.webp', '/coloring-pages/architecture-landscapes/hexagonal-boardwalk/color.webp', '/coloring-pages/architecture-landscapes/hexagonal-boardwalk/line-art.webp', 0, 'published', 523, 'standard:places:hexagonal-boardwalk'),
  ('page-places-evergreen-tree', 'standard', 'Evergreen Tree Coloring Page', 'evergreen-tree', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/evergreen-tree/line-art.webp', '/coloring-pages/architecture-landscapes/evergreen-tree/color.webp', '/coloring-pages/architecture-landscapes/evergreen-tree/line-art.webp', 0, 'published', 524, 'standard:places:evergreen-tree'),
  ('page-places-old-tree-trunk', 'standard', 'Old Tree Trunk Coloring Page', 'old-tree-trunk', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/old-tree-trunk/line-art.webp', '/coloring-pages/architecture-landscapes/old-tree-trunk/color.webp', '/coloring-pages/architecture-landscapes/old-tree-trunk/line-art.webp', 0, 'published', 525, 'standard:places:old-tree-trunk'),
  ('page-places-waterside-courtyard', 'standard', 'Waterside Courtyard Coloring Page', 'waterside-courtyard', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/waterside-courtyard/line-art.webp', '/coloring-pages/architecture-landscapes/waterside-courtyard/color.webp', '/coloring-pages/architecture-landscapes/waterside-courtyard/line-art.webp', 0, 'published', 526, 'standard:places:waterside-courtyard'),
  ('page-places-stepping-stone-garden', 'standard', 'Stepping Stone Garden Coloring Page', 'stepping-stone-garden', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/stepping-stone-garden/line-art.webp', '/coloring-pages/architecture-landscapes/stepping-stone-garden/color.webp', '/coloring-pages/architecture-landscapes/stepping-stone-garden/line-art.webp', 0, 'published', 527, 'standard:places:stepping-stone-garden'),
  ('page-places-traditional-pavilion', 'standard', 'Traditional Pavilion Coloring Page', 'traditional-pavilion', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/traditional-pavilion/line-art.webp', '/coloring-pages/architecture-landscapes/traditional-pavilion/color.webp', '/coloring-pages/architecture-landscapes/traditional-pavilion/line-art.webp', 0, 'published', 528, 'standard:places:traditional-pavilion'),
  ('page-places-city-street', 'standard', 'City Street Coloring Page', 'city-street', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/city-street/line-art.webp', '/coloring-pages/architecture-landscapes/city-street/color.webp', '/coloring-pages/architecture-landscapes/city-street/line-art.webp', 0, 'published', 529, 'standard:places:city-street'),
  ('page-places-traditional-courtyard', 'standard', 'Traditional Courtyard Coloring Page', 'traditional-courtyard', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/traditional-courtyard/line-art.webp', '/coloring-pages/architecture-landscapes/traditional-courtyard/color.webp', '/coloring-pages/architecture-landscapes/traditional-courtyard/line-art.webp', 0, 'published', 530, 'standard:places:traditional-courtyard'),
  ('page-places-urban-park', 'standard', 'Urban Park Coloring Page', 'urban-park', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/urban-park/line-art.webp', '/coloring-pages/architecture-landscapes/urban-park/color.webp', '/coloring-pages/architecture-landscapes/urban-park/line-art.webp', 0, 'published', 531, 'standard:places:urban-park'),
  ('page-places-contemporary-house-garden', 'standard', 'Contemporary House Garden Coloring Page', 'contemporary-house-garden', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/contemporary-house-garden/line-art.webp', '/coloring-pages/architecture-landscapes/contemporary-house-garden/color.webp', '/coloring-pages/architecture-landscapes/contemporary-house-garden/line-art.webp', 0, 'published', 532, 'standard:places:contemporary-house-garden'),
  ('page-places-palm-island-shoreline', 'standard', 'Palm Island Shoreline Coloring Page', 'palm-island-shoreline', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/palm-island-shoreline/line-art.webp', '/coloring-pages/architecture-landscapes/palm-island-shoreline/color.webp', '/coloring-pages/architecture-landscapes/palm-island-shoreline/line-art.webp', 0, 'published', 533, 'standard:places:palm-island-shoreline'),
  ('page-places-decorative-gate-courtyard', 'standard', 'Decorative Gate Courtyard Coloring Page', 'decorative-gate-courtyard', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/decorative-gate-courtyard/line-art.webp', '/coloring-pages/architecture-landscapes/decorative-gate-courtyard/color.webp', '/coloring-pages/architecture-landscapes/decorative-gate-courtyard/line-art.webp', 0, 'published', 534, 'standard:places:decorative-gate-courtyard'),
  ('page-places-village-reflection', 'standard', 'Village Reflection Coloring Page', 'village-reflection', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/village-reflection/line-art.webp', '/coloring-pages/architecture-landscapes/village-reflection/color.webp', '/coloring-pages/architecture-landscapes/village-reflection/line-art.webp', 0, 'published', 535, 'standard:places:village-reflection'),
  ('page-places-forested-lakeshore', 'standard', 'Forested Lakeshore Coloring Page', 'forested-lakeshore', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/forested-lakeshore/line-art.webp', '/coloring-pages/architecture-landscapes/forested-lakeshore/color.webp', '/coloring-pages/architecture-landscapes/forested-lakeshore/line-art.webp', 0, 'published', 536, 'standard:places:forested-lakeshore'),
  ('page-places-fantasy-treehouse', 'standard', 'Fantasy Treehouse Coloring Page', 'fantasy-treehouse', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/fantasy-treehouse/line-art.webp', '/coloring-pages/architecture-landscapes/fantasy-treehouse/color.webp', '/coloring-pages/architecture-landscapes/fantasy-treehouse/line-art.webp', 0, 'published', 537, 'standard:places:fantasy-treehouse'),
  ('page-places-garden-bridge', 'standard', 'Garden Bridge Coloring Page', 'garden-bridge', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/garden-bridge/line-art.webp', '/coloring-pages/architecture-landscapes/garden-bridge/color.webp', '/coloring-pages/architecture-landscapes/garden-bridge/line-art.webp', 0, 'published', 538, 'standard:places:garden-bridge'),
  ('page-places-river-cityscape', 'standard', 'River Cityscape Coloring Page', 'river-cityscape', 'Detailed architecture and landscape illustration.', '/coloring-pages/architecture-landscapes/river-cityscape/line-art.webp', '/coloring-pages/architecture-landscapes/river-cityscape/color.webp', '/coloring-pages/architecture-landscapes/river-cityscape/line-art.webp', 0, 'published', 539, 'standard:places:river-cityscape');

INSERT OR IGNORE INTO page_categories (page_id, category_id, is_primary)
SELECT id, 'cat-architecture-landscapes', 1 FROM coloring_pages
WHERE source_key LIKE 'standard:places:%';
