-- Sci-fi, fantasy, action, and vehicle printables. Safe to re-run.
PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO categories (id, name, slug, description, sort_order, status) VALUES
  ('cat-sci-fi-robots', 'Sci-Fi & Robots', 'sci-fi-robots', 'Robots, cyborgs, mechs, and imaginative space-age machines to color.', 34, 'published'),
  ('cat-action-adventure', 'Action & Adventure', 'action-adventure', 'Bold explorers, armored heroes, and action-packed scenes to color.', 35, 'published'),
  ('cat-fantasy-warriors', 'Fantasy Warriors', 'fantasy-warriors', 'Armored knights, enchanted fighters, and heroic fantasy scenes to color.', 36, 'published'),
  ('cat-vehicles', 'Vehicles', 'vehicles', 'Things that move, ready to color.', 37, 'published');

UPDATE categories SET status = 'published' WHERE id = 'cat-vehicles';

INSERT OR IGNORE INTO coloring_pages (
  id, content_type, title, slug, short_description, line_art_url, color_reference_url,
  thumbnail_url, featured, status, sort_order, source_key
) VALUES
  ('page-scifi-armored-future-soldier', 'standard', 'Armored Future Soldier Coloring Page', 'armored-future-soldier', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/armored-future-soldier-line.jpg', '/coloring-pages/scifi-action/armored-future-soldier-color.jpg', '/coloring-pages/scifi-action/armored-future-soldier-line.jpg', 1, 'published', 600, 'standard:scifi:armored-future-soldier'),
  ('page-scifi-cyborg-sentinel', 'standard', 'Cyborg Sentinel Coloring Page', 'cyborg-sentinel', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/cyborg-sentinel-line.jpg', '/coloring-pages/scifi-action/cyborg-sentinel-color.jpg', '/coloring-pages/scifi-action/cyborg-sentinel-line.jpg', 1, 'published', 601, 'standard:scifi:cyborg-sentinel'),
  ('page-scifi-blue-gold-exosuit-warrior', 'standard', 'Blue-Gold Exosuit Warrior Coloring Page', 'blue-gold-exosuit-warrior', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/blue-gold-exosuit-warrior-line.jpg', '/coloring-pages/scifi-action/blue-gold-exosuit-warrior-color.jpg', '/coloring-pages/scifi-action/blue-gold-exosuit-warrior-line.jpg', 1, 'published', 602, 'standard:scifi:blue-gold-exosuit-warrior'),
  ('page-scifi-tech-ranger', 'standard', 'Tech Ranger Coloring Page', 'tech-ranger', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/tech-ranger-line.jpg', '/coloring-pages/scifi-action/tech-ranger-color.jpg', '/coloring-pages/scifi-action/tech-ranger-line.jpg', 1, 'published', 603, 'standard:scifi:tech-ranger'),
  ('page-scifi-neon-armored-scout', 'standard', 'Neon Armored Scout Coloring Page', 'neon-armored-scout', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/neon-armored-scout-line.jpg', '/coloring-pages/scifi-action/neon-armored-scout-color.jpg', '/coloring-pages/scifi-action/neon-armored-scout-line.jpg', 1, 'published', 604, 'standard:scifi:neon-armored-scout'),
  ('page-scifi-heavy-power-armor', 'standard', 'Heavy Power Armor Coloring Page', 'heavy-power-armor', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/heavy-power-armor-line.jpg', '/coloring-pages/scifi-action/heavy-power-armor-color.jpg', '/coloring-pages/scifi-action/heavy-power-armor-line.jpg', 1, 'published', 605, 'standard:scifi:heavy-power-armor'),
  ('page-scifi-shoulder-launcher-soldier', 'standard', 'Shoulder Launcher Soldier Coloring Page', 'shoulder-launcher-soldier', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/shoulder-launcher-soldier-line.jpg', '/coloring-pages/scifi-action/shoulder-launcher-soldier-color.jpg', '/coloring-pages/scifi-action/shoulder-launcher-soldier-line.jpg', 0, 'published', 606, 'standard:scifi:shoulder-launcher-soldier'),
  ('page-scifi-power-suit-adventurer', 'standard', 'Power Suit Adventurer Coloring Page', 'power-suit-adventurer', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/power-suit-adventurer-line.jpg', '/coloring-pages/scifi-action/power-suit-adventurer-color.jpg', '/coloring-pages/scifi-action/power-suit-adventurer-line.jpg', 0, 'published', 607, 'standard:scifi:power-suit-adventurer'),
  ('page-scifi-cybernetic-heavy-gunner', 'standard', 'Cybernetic Heavy Gunner Coloring Page', 'cybernetic-heavy-gunner', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/cybernetic-heavy-gunner-line.jpg', '/coloring-pages/scifi-action/cybernetic-heavy-gunner-color.jpg', '/coloring-pages/scifi-action/cybernetic-heavy-gunner-line.jpg', 0, 'published', 608, 'standard:scifi:cybernetic-heavy-gunner'),
  ('page-scifi-spider-tank', 'standard', 'Spider Tank Coloring Page', 'spider-tank', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/spider-tank-line.jpg', '/coloring-pages/scifi-action/spider-tank-color.jpg', '/coloring-pages/scifi-action/spider-tank-line.jpg', 0, 'published', 609, 'standard:scifi:spider-tank'),
  ('page-scifi-futuristic-female-adventurer', 'standard', 'Futuristic Female Adventurer Coloring Page', 'futuristic-female-adventurer', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/futuristic-female-adventurer-line.jpg', '/coloring-pages/scifi-action/futuristic-female-adventurer-color.jpg', '/coloring-pages/scifi-action/futuristic-female-adventurer-line.jpg', 0, 'published', 610, 'standard:scifi:futuristic-female-adventurer'),
  ('page-scifi-fantasy-spear-warrior', 'standard', 'Fantasy Spear Warrior Coloring Page', 'fantasy-spear-warrior', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/fantasy-spear-warrior-line.jpg', '/coloring-pages/scifi-action/fantasy-spear-warrior-color.jpg', '/coloring-pages/scifi-action/fantasy-spear-warrior-line.jpg', 0, 'published', 611, 'standard:scifi:fantasy-spear-warrior'),
  ('page-scifi-elf-tech-sword-fighter', 'standard', 'Elf Tech Sword Fighter Coloring Page', 'elf-tech-sword-fighter', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/elf-tech-sword-fighter-line.jpg', '/coloring-pages/scifi-action/elf-tech-sword-fighter-color.jpg', '/coloring-pages/scifi-action/elf-tech-sword-fighter-line.jpg', 0, 'published', 612, 'standard:scifi:elf-tech-sword-fighter'),
  ('page-scifi-tactical-female-scout', 'standard', 'Tactical Female Scout Coloring Page', 'tactical-female-scout', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/tactical-female-scout-line.jpg', '/coloring-pages/scifi-action/tactical-female-scout-color.jpg', '/coloring-pages/scifi-action/tactical-female-scout-line.jpg', 0, 'published', 613, 'standard:scifi:tactical-female-scout'),
  ('page-scifi-wasteland-sniper', 'standard', 'Wasteland Sniper Coloring Page', 'wasteland-sniper', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/wasteland-sniper-line.jpg', '/coloring-pages/scifi-action/wasteland-sniper-color.jpg', '/coloring-pages/scifi-action/wasteland-sniper-line.jpg', 0, 'published', 614, 'standard:scifi:wasteland-sniper'),
  ('page-scifi-bionic-backpack-explorer', 'standard', 'Bionic Backpack Explorer Coloring Page', 'bionic-backpack-explorer', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/bionic-backpack-explorer-line.jpg', '/coloring-pages/scifi-action/bionic-backpack-explorer-color.jpg', '/coloring-pages/scifi-action/bionic-backpack-explorer-line.jpg', 0, 'published', 615, 'standard:scifi:bionic-backpack-explorer'),
  ('page-scifi-armored-space-squad', 'standard', 'Armored Space Squad Coloring Page', 'armored-space-squad', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/armored-space-squad-line.jpg', '/coloring-pages/scifi-action/armored-space-squad-color.jpg', '/coloring-pages/scifi-action/armored-space-squad-line.jpg', 0, 'published', 616, 'standard:scifi:armored-space-squad'),
  ('page-scifi-mech-pilot-combat-pod', 'standard', 'Mech Pilot Combat Pod Coloring Page', 'mech-pilot-combat-pod', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/mech-pilot-combat-pod-line.jpg', '/coloring-pages/scifi-action/mech-pilot-combat-pod-color.jpg', '/coloring-pages/scifi-action/mech-pilot-combat-pod-line.jpg', 0, 'published', 617, 'standard:scifi:mech-pilot-combat-pod'),
  ('page-scifi-mech-pilot-launch-console', 'standard', 'Mech Pilot Launch Console Coloring Page', 'mech-pilot-launch-console', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/mech-pilot-launch-console-line.jpg', '/coloring-pages/scifi-action/mech-pilot-launch-console-color.jpg', '/coloring-pages/scifi-action/mech-pilot-launch-console-line.jpg', 0, 'published', 618, 'standard:scifi:mech-pilot-launch-console'),
  ('page-scifi-grenade-lance-scout', 'standard', 'Grenade Lance Scout Coloring Page', 'grenade-lance-scout', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/grenade-lance-scout-line.jpg', '/coloring-pages/scifi-action/grenade-lance-scout-color.jpg', '/coloring-pages/scifi-action/grenade-lance-scout-line.jpg', 0, 'published', 619, 'standard:scifi:grenade-lance-scout'),
  ('page-scifi-armored-expedition-explorer', 'standard', 'Armored Expedition Explorer Coloring Page', 'armored-expedition-explorer', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/armored-expedition-explorer-line.jpg', '/coloring-pages/scifi-action/armored-expedition-explorer-color.jpg', '/coloring-pages/scifi-action/armored-expedition-explorer-line.jpg', 0, 'published', 620, 'standard:scifi:armored-expedition-explorer'),
  ('page-scifi-heavy-futuristic-trooper', 'standard', 'Heavy Futuristic Trooper Coloring Page', 'heavy-futuristic-trooper', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/heavy-futuristic-trooper-line.jpg', '/coloring-pages/scifi-action/heavy-futuristic-trooper-color.jpg', '/coloring-pages/scifi-action/heavy-futuristic-trooper-line.jpg', 0, 'published', 621, 'standard:scifi:heavy-futuristic-trooper'),
  ('page-scifi-cybernetic-woman-portrait', 'standard', 'Cybernetic Woman Portrait Coloring Page', 'cybernetic-woman-portrait', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/cybernetic-woman-portrait-line.jpg', '/coloring-pages/scifi-action/cybernetic-woman-portrait-color.jpg', '/coloring-pages/scifi-action/cybernetic-woman-portrait-line.jpg', 0, 'published', 622, 'standard:scifi:cybernetic-woman-portrait'),
  ('page-scifi-alien-mech-creature', 'standard', 'Alien Mech Creature Coloring Page', 'alien-mech-creature', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/alien-mech-creature-line.jpg', '/coloring-pages/scifi-action/alien-mech-creature-color.jpg', '/coloring-pages/scifi-action/alien-mech-creature-line.jpg', 0, 'published', 623, 'standard:scifi:alien-mech-creature'),
  ('page-scifi-winter-heavy-gunner', 'standard', 'Winter Heavy Gunner Coloring Page', 'winter-heavy-gunner', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/winter-heavy-gunner-line.jpg', '/coloring-pages/scifi-action/winter-heavy-gunner-color.jpg', '/coloring-pages/scifi-action/winter-heavy-gunner-line.jpg', 0, 'published', 624, 'standard:scifi:winter-heavy-gunner'),
  ('page-scifi-mechanical-arm-train-window', 'standard', 'Mechanical Arm at the Train Window Coloring Page', 'mechanical-arm-train-window', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/mechanical-arm-train-window-line.jpg', '/coloring-pages/scifi-action/mechanical-arm-train-window-color.jpg', '/coloring-pages/scifi-action/mechanical-arm-train-window-line.jpg', 0, 'published', 625, 'standard:scifi:mechanical-arm-train-window'),
  ('page-scifi-racing-trimaran', 'standard', 'Racing Trimaran Coloring Page', 'racing-trimaran', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/racing-trimaran-line.jpg', '/coloring-pages/scifi-action/racing-trimaran-color.jpg', '/coloring-pages/scifi-action/racing-trimaran-line.jpg', 0, 'published', 626, 'standard:scifi:racing-trimaran'),
  ('page-scifi-arcane-mech-warriors', 'standard', 'Arcane Mech Warriors Coloring Page', 'arcane-mech-warriors', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/arcane-mech-warriors-line.jpg', '/coloring-pages/scifi-action/arcane-mech-warriors-color.jpg', '/coloring-pages/scifi-action/arcane-mech-warriors-line.jpg', 0, 'published', 627, 'standard:scifi:arcane-mech-warriors'),
  ('page-scifi-robot-commander-walker', 'standard', 'Robot Commander Walker Coloring Page', 'robot-commander-walker', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/robot-commander-walker-line.jpg', '/coloring-pages/scifi-action/robot-commander-walker-color.jpg', '/coloring-pages/scifi-action/robot-commander-walker-line.jpg', 0, 'published', 628, 'standard:scifi:robot-commander-walker'),
  ('page-scifi-futuristic-fighter-plane', 'standard', 'Futuristic Fighter Plane Coloring Page', 'futuristic-fighter-plane', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/futuristic-fighter-plane-line.jpg', '/coloring-pages/scifi-action/futuristic-fighter-plane-color.jpg', '/coloring-pages/scifi-action/futuristic-fighter-plane-line.jpg', 0, 'published', 629, 'standard:scifi:futuristic-fighter-plane'),
  ('page-scifi-mechanical-crab-explorer', 'standard', 'Mechanical Crab Explorer Coloring Page', 'mechanical-crab-explorer', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/mechanical-crab-explorer-line.jpg', '/coloring-pages/scifi-action/mechanical-crab-explorer-color.jpg', '/coloring-pages/scifi-action/mechanical-crab-explorer-line.jpg', 0, 'published', 630, 'standard:scifi:mechanical-crab-explorer'),
  ('page-scifi-winged-flying-robot', 'standard', 'Winged Flying Robot Coloring Page', 'winged-flying-robot', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/winged-flying-robot-line.jpg', '/coloring-pages/scifi-action/winged-flying-robot-color.jpg', '/coloring-pages/scifi-action/winged-flying-robot-line.jpg', 0, 'published', 631, 'standard:scifi:winged-flying-robot'),
  ('page-scifi-alien-jetpack-creature', 'standard', 'Alien Jetpack Creature Coloring Page', 'alien-jetpack-creature', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/alien-jetpack-creature-line.jpg', '/coloring-pages/scifi-action/alien-jetpack-creature-color.jpg', '/coloring-pages/scifi-action/alien-jetpack-creature-line.jpg', 0, 'published', 632, 'standard:scifi:alien-jetpack-creature'),
  ('page-scifi-alien-crab-laser-beast', 'standard', 'Alien Crab Laser Beast Coloring Page', 'alien-crab-laser-beast', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/alien-crab-laser-beast-line.jpg', '/coloring-pages/scifi-action/alien-crab-laser-beast-color.jpg', '/coloring-pages/scifi-action/alien-crab-laser-beast-line.jpg', 0, 'published', 633, 'standard:scifi:alien-crab-laser-beast'),
  ('page-scifi-tech-sniper', 'standard', 'Tech Sniper Coloring Page', 'tech-sniper', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/tech-sniper-line.jpg', '/coloring-pages/scifi-action/tech-sniper-color.jpg', '/coloring-pages/scifi-action/tech-sniper-line.jpg', 0, 'published', 634, 'standard:scifi:tech-sniper'),
  ('page-scifi-cyborg-portrait', 'standard', 'Cyborg Portrait Coloring Page', 'cyborg-portrait', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/cyborg-portrait-line.jpg', '/coloring-pages/scifi-action/cyborg-portrait-color.jpg', '/coloring-pages/scifi-action/cyborg-portrait-line.jpg', 0, 'published', 635, 'standard:scifi:cyborg-portrait'),
  ('page-scifi-spiked-knight-armor', 'standard', 'Spiked Knight Armor Coloring Page', 'spiked-knight-armor', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/spiked-knight-armor-line.jpg', '/coloring-pages/scifi-action/spiked-knight-armor-color.jpg', '/coloring-pages/scifi-action/spiked-knight-armor-line.jpg', 0, 'published', 636, 'standard:scifi:spiked-knight-armor'),
  ('page-scifi-visor-cyborg', 'standard', 'Visor Cyborg Coloring Page', 'visor-cyborg', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/visor-cyborg-line.jpg', '/coloring-pages/scifi-action/visor-cyborg-color.jpg', '/coloring-pages/scifi-action/visor-cyborg-line.jpg', 0, 'published', 637, 'standard:scifi:visor-cyborg'),
  ('page-scifi-alien-blade-warrior', 'standard', 'Alien Blade Warrior Coloring Page', 'alien-blade-warrior', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/alien-blade-warrior-line.jpg', '/coloring-pages/scifi-action/alien-blade-warrior-color.jpg', '/coloring-pages/scifi-action/alien-blade-warrior-line.jpg', 0, 'published', 638, 'standard:scifi:alien-blade-warrior'),
  ('page-scifi-heavy-gun-motorcycle-rider', 'standard', 'Heavy-Gun Motorcycle Rider Coloring Page', 'heavy-gun-motorcycle-rider', 'Detailed sci-fi, fantasy, or action printable illustration.', '/coloring-pages/scifi-action/heavy-gun-motorcycle-rider-line.jpg', '/coloring-pages/scifi-action/heavy-gun-motorcycle-rider-color.jpg', '/coloring-pages/scifi-action/heavy-gun-motorcycle-rider-line.jpg', 0, 'published', 639, 'standard:scifi:heavy-gun-motorcycle-rider');

INSERT OR REPLACE INTO page_categories (page_id, category_id, is_primary)
SELECT id,
  CASE
    WHEN slug IN ('racing-trimaran', 'futuristic-fighter-plane') THEN 'cat-vehicles'
    WHEN slug IN ('fantasy-spear-warrior', 'elf-tech-sword-fighter', 'arcane-mech-warriors', 'spiked-knight-armor') THEN 'cat-fantasy-warriors'
    WHEN slug IN ('shoulder-launcher-soldier', 'tactical-female-scout', 'wasteland-sniper', 'armored-space-squad', 'grenade-lance-scout', 'tech-sniper', 'heavy-gun-motorcycle-rider') THEN 'cat-action-adventure'
    ELSE 'cat-sci-fi-robots'
  END,
  1
FROM coloring_pages
WHERE source_key LIKE 'standard:scifi:%';
